name: lint text
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited]
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: lint text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get node version from Dockerfile
        id: node-version
        run: |
          echo "node-version=$(head -1 Dockerfile | sed 's/FROM node://g')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: '${{steps.node-version.outputs.node-version}}'
          cache: yarn
      - run: npm install
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: lint text
        run: npm run lint:ci > .textlint.log
      - name: Run Reviewdog
        if: failure() && github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat .textlint.log
          cat .textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
