name: PDF
on:
  pull_request:
    paths:
      - .github/workflows/pdf.yml # self
      - docs/*
      - pdf-configs/*
      - yarn.lock
  push:
    tags:
    - 'v*'
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Get node version from Dockerfile
        id: node-version
        run: |
          echo "node-version=$(head -1 Dockerfile | sed 's/FROM node://g' | sed -E 's/([0-9]+)\-.*/\1/g')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '${{steps.node-version.outputs.node-version}}'
          cache: yarn
      - run: npm install
      - name: build pdf
        run: |
          npm run build:pdf
          mv docs/README.pdf docs/resume.pdf
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: resume
          path: ./docs/resume.pdf
          if-no-files-found: error
          retention-days: 7
  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: resume
          path: docs
      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          files: docs/resume.pdf
          draft: true
          prerelease: false
